### PR TITLE
Change operator from cluster-scoped to namespace-scoped

### PR DESCRIPTION
**Pull request by mandydydy**

### CODE REVIEW

**Comment by mandydydy** [comment]
https://github.com/Nordix/Meridio/issues/68

**Review by LionelJouin — COMMENTED** [review]
The Operator will now watch the changes only in its namespace as expected, but its RBAC permissions are still applied to the cluster instead of only in the watched namespace. As described in the operator SDK documentation, I think we should modify it, but not sure how with our specific case.
https://sdk.operatorframework.io/docs/building-operators/golang/operator-scope/#restricting-roles-and-permissions

**Comment by mandydydy** [comment]
You're right. I forgot about the rbac. I will do a fix soon.

**Comment by LionelJouin** [comment]
I am not sure if you can easily, I think the RBAC markers to generate the rbac files are static. You could set namespace={{ .Release.Namespace }}, so it might work for the helm chart, but not the the "make deploy" with kustomize. 
And if you change it directly in the yaml files, "make manifests" will overwrite your changes.

**Comment by mandydydy** [comment]
kustomize should have a corresponding function to replace the namespace. I think we need to guarantee that kustomize will work. Helm is not really supported here now.

**Review by LionelJouin — APPROVED** [review]

**Review by LionelJouin — APPROVED** [review]

**Pull request merged**
